name: SellAll
main: me.ShanaChans.SellAll.SellAllManager
author: [ShanaChans]
depend: [NeoCore, Vault]
version: 1.0
api-version: 1.16
commands:
   sellall:
       description: Sell all the goods in your inventory!
       usage: /sellall
   selladmin:
       description: Admin commands for sellall
       usage: /selladmin
   value:
       description: Get the value of the item in your hand!
       usage: /value